=== FTalour/Mes-Projets-Java/JMS Exercice 7/commande.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns 			= "http://www.w3.org/2001/XMLSchema" 
	targetNamespace		= "http://www.example.org/commande" 
	xmlns:tns			= "http://www.example.org/commande"
	elementFormDefault 	= "qualified">

    <element name="commande">
	     <complexType>
	    	<sequence>
	    		<element name="reference" type="string"></element>
	    		<element name="date" type="date"/>
	    		<element name="produits" type="tns:produits"/>
	    	</sequence>
	    </complexType>
    </element>
  
	<complexType name="produits">
		<sequence>
			<element name="produit" type="tns:produit" minOccurs="1" maxOccurs="unbounded" />
		</sequence>
	</complexType>
  	
    <complexType name="produit">
    	<sequence>
	    	<element name="reference" type="string"></element>
	    	<element name="quantite" type="int"></element>
	    	<element name="prix" type="int" minOccurs="0"></element>
    	</sequence>
    </complexType>
    
   
    
</schema>

=== FTalour/Mes-Projets-Java/JMS Exercice 7/maCommande.xml
<?xml version="1.0" encoding="UTF-8" ?>
<commande xmlns  				= "http://www.example.org/commande"
		  xmlns:xsi				= "http://www.w3.org/2001/XMLSchema-instance"
		  xsi:schemaLocation 	= "http://www.example.org/commande commande.xsd">
	<reference>refcommande1</reference>
	<date>2016-10-21-10:30</date>
	<produits>
		<produit>
			<reference>refproduit1</reference>
			<quantite>10</quantite>
			<prix></prix>
		</produit>
		<produit>
			<reference>refproduit2</reference>
			<quantite>5</quantite>
			<prix></prix>
		</produit>
	</produits>
</commande>
