=== FTalour/Mes-Projets-Java/JMS/JMS Entreprise-V3/entreprise_V3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="http://www.leuville.com/entreprise2" 
	xmlns:tns="http://www.leuville.com/entreprise2" 
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">

	<xsd:element name="entreprise" type="tns:entreprise" />

	<xsd:complexType name="entreprise">
		<xsd:sequence>
			<xsd:element name="raison-sociale"
				type="tns:raison-sociale" />
			<xsd:element name="departements">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="departement"
							type="tns:departement" maxOccurs="unbounded" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="departement">
		<xsd:sequence>
			<xsd:element name="intitule" type="xsd:string" />
			<xsd:element name="responsable" type="xsd:string" />
			<xsd:element name="adjoint" type="xsd:string" minOccurs="0" />
			<xsd:element name="membres">
				<xsd:complexType>
					<xsd:sequence>
						<xsd:element name="nom" type="xsd:string"
									maxOccurs="unbounded" />
					</xsd:sequence>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="raison-sociale">
		<xsd:sequence>
			<xsd:element name="nom" type="xsd:string" />
			<xsd:element name="adresse" type="xsd:string" />
			<xsd:element name="forme" type="tns:forme-juridique" />
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:simpleType name="forme-juridique">
	  <xsd:restriction base="xsd:string">
	    <xsd:enumeration value="SA" />
	    <xsd:enumeration value="SARL" />
	  </xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== FTalour/Mes-Projets-Java/JMS Entreprise-V3/entreprise_xsd_V3.xml
<?xml version="1.0" encoding="UTF-8"?>

<entreprise xmlns="http://www.leuville.com/entreprise2" 
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
            xsi:schemaLocation="http://www.leuville.com/entreprise2 entreprise_V3.xsd">
	<raison-sociale>
	  <nom>Leuville Objects</nom>
	  <adresse>3 rue de la Porte de Buc</adresse>
	  <forme>SA</forme>
	</raison-sociale>
	<departements>
	  <departement>
	    <intitule>Formation</intitule>
	    <responsable>Philippe Hubert</responsable>
	    <adjoint>Richard Lecomte</adjoint>
	    <membres>
	      <nom>Richard Lecomte</nom>
	      <nom>Philippe Hubert</nom>
	    </membres>
	  </departement>
	  <departement>
	    <intitule>Commercial</intitule>
	    <responsable>Damien de Verneuil</responsable>
	    <membres>
	      <nom>Gaston Lagaffe</nom>
	    </membres>
	  </departement>
	</departements>
</entreprise>
